title: Tom Drake
slogan: Technical Writing, Product Documentation Strategy, Information Architecture, Front-end Development

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
