title: Tom Drake
slogan: Technical Writing, Product Documentation Strategy, Information Architecture, Front-end Development
summary:
  - Technical communications professional with over 10 years of experience in app software product documentation, information architecture, documentation content strategy, front-end development, UX, agile development, and SME collaboration.
  - Expertise in Jekyll, Github, DITA XML, HTML5, CSS, JavaScript, Python, Adobe Creative Suite, project management, independent research, and proposal development.
  - Father, husband, dog owner, enthusiast of X-Men comics from the early 1990s.
  - Ames, IA > Austin, TX > Greater Chicago Area, IL

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
